In [1]:
import os
import subprocess
import pandas as pd

import math
import random
from typing import List, Tuple
from PIL import Image
from PIL import ImageDraw
import matplotlib.pyplot as plt

from tqdm import tqdm

df = pd.DataFrame(columns = ["S.No.", "No. of Vertices", "No. of Notches", "Execution Time"])
# df.columns = ["S.No.", "No. of Vertices", "No. of Notches", "Execution Time"]
df["S.No."] = df["S.No."].astype(int)
df["No. of Vertices"] = df["No. of Vertices"].astype(int)
df["No. of Notches"] = df["No. of Notches"].astype(int)


cpp_name = "htester_final_1.cpp"
num_ips = 1000

if(os.system('g++ ' + cpp_name) == 0):
    for i in tqdm(range(750, num_ips + 1)):
        # print(i)
        f = open("input" + str(i) + ".txt", "r")
        ln = f.readline().rstrip()
        f.close()

        proc = subprocess.run("./a.exe input"+ str(i) + ".txt", capture_output = True, text = True)
        
        notches, time = proc.stdout.rstrip().splitlines()
        notches = int(notches)
        time = float(time) / 1000
        
        #   [S.No., no. of verts, no. of notches, execution time]
        l = [int(i), int(ln), int(notches), time]
        df.loc[len(df)] = l

        # proc = subprocess.run("./a.exe ipL.txt", capture_output = True, text = True)
        # print(proc.stdout.rstrip())

        file1 = open("opinput" + str(i) + ".txt", "r")
        lines = file1.readlines()

        all_poly = []

        for line in lines:
            poly = []
            items = line.rstrip().split()
            for k in range(0, len(items),2):
                x = float(items[k])
                y = float(items[k + 1])
                poly.append([x, y])
                
            # print(poly)
            all_poly.append(poly)
            
        # # print(all_poly)
        # print(all_poly)

        plt.figure()
        for j in range(len(all_poly)):
            all_poly[j].append(all_poly[j][0])
            xs, ys = zip(*(all_poly[j]))
            if j == (len(all_poly) - 1):
                plt.plot(xs,ys, color = "black")
            else:
                plt.plot(xs,ys, color = "red")
                # D:\Studies\4-2 Courses\CS F364 - DAA\Assignment\final version\figs
                # "D:/Studies/4-2 Courses/CS F364 - DAA/Assignment/final version/figs/img"
        # plt.savefig("/Users/aryankapadia/Desktop/2019B3A70630H_CSF364_A1/Ouputs/output15.jpg")
        plt.savefig("figs/img" + str(i) + ".jpg")
        # plt.show()
        plt.clf()

df

  0%|          | 0/251 [03:04<?, ?it/s]

ValueError: not enough values to unpack (expected 2, got 1)

In [ ]:
df

In [ ]:
df.to_excel("first293.xlsx")

In [33]:
df = pd.read_excel("All_test_cases.xlsx", index_col = 0)
df

     S.No.  No. of Vertices  No. of Notches  Execution Time
0        1                6               1           0.790
1        2                8               1           0.160
2        3               11               2           0.201
3        4               12               3           0.219
4        5               15               4           0.342
..     ...              ...             ...             ...
746    747             3804            1785       45646.547
747    748             3807            1782       45067.773
748    749             3808            1803       45991.422
749    750             3809            1775       45490.663
750    751             3812            1774       44692.450

[751 rows x 4 columns]